image: Visual Studio 2019

os: unstable

platform:
  - x86
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm install

build_script:
  - npm run test
  - npm run build

test: false
