enum WorkerTypes {
  COMPILE = 'COMPILE',
  EXTRACT = 'EXTRACT',
  GENERATE_ANSWER_SHEET = 'GENERATE_ANSWER_SHEET',
  GENERATE_TEST_DATA = 'GENERATE_TEST_DATA',
  TRAIN = 'TRAIN',
}

export default WorkerTypes
